version: 2
updates:
  - package-ecosystem: "gitsubmodule" # Track official and unleashed firmware as a submodule
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
